openapi: 3.0.0
info:
  title: CIVOP API
  version: 1.0.0
  description: API for managing control tasks
  
  

paths:
  /api/control_Task:
    post:
      summary: Create an internal ID for a control task based on the supplier's task details.
      description: Accepts a supplier's task ID and title to generate and return a new internal task ID for creating related documents and defects.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: controlTask
              properties:
                civopControlTaskId:
                  type: integer
                  description: The unique identifier of the supplier's control task.
                title:
                  type: string
                  description: A brief title for the control task.
      responses:
        200:
          description: Successfully retrieved control task details
          content:
            application/json:
              schema:
                type: object
                title: controlTask
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the control task.
                  civopControlTaskId:
                    type: integer
                    description: The unique identifier of the supplier's control task.
                  title:
                    type: string
                    description: A brief title for the control task.
                  created_at:
                    type: string
                    format: date-time
                    description: The timestamp when the control task was created.
        404:
          description: Control task not found
        500:
          description: Internal server error


  /api/control_task/{controlTaskId}/document:
    post:
      summary: Create a new document related to a control task
      description: Create a new document for the given control task identified by {controlTaskId}.
      parameters:
        - name: controlTaskId
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier of the control task to which the document will be added.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: controlTaskId/document
              properties:
                filename:
                  type: string
                  description: The filename of the document to be added.
                contentType:
                  type: string
                  description: The content type of the document (e.g., application/pdf, image/jpeg).
                base64Data:
                  type: string
                  description: The base64 encoded content of the document.
                specialist:
                  type: string
                  description: The specialist associated with the document.
                inspectionDate:
                  type: string
                  format: date
                  description: The date of the inspection.
                numberOfDefects:
                  type: integer
                  description: The total number of defects found during the inspection.
                codesOfDefects:
                    type: array
                    items:
                      type: integer
                    description: A list of codes identifying the defects found.
                pictures:
                  type: array
                  items:
                    type: object
                    properties:
                      filename:
                        type: string
                        description: The filename of the image.
                      contentType:
                        type: string
                        description: The MIME type of the image.
                      base64Data:
                        type: string
                        description: Base64 encoded image data.
                additionalDocuments:
                  type: array
                  items:
                    type: object
                    properties:
                      filename:
                        type: string
                        description: The filename of the additional document.
                      contentType:
                        type: string
                        description: The MIME type of the additional document.
                      base64Data:
                        type: string
                        description: Base64 encoded additional document data.
      responses:
        200:
          description: Document successfully created
          content:
            application/json:
              schema:
                type: object
                title: controlTaskId/document
                properties:
                  createdDocument:
                    type: object
                    properties:                      
                      id:
                        type: integer
                        description: A unique identifier for the document.
                      controlTaskId:
                        type: integer
                        description: The unique identifier of the control task.
                      message:
                        type: string
                        description: Success message indicating that the document was created.
                      filename:
                        type: string
                      contentType:
                        type: string
                      specialist:
                        type: string
                      inspectionDate:
                        type: string
                        format: date
                      numberOfDefects:
                        type: integer
                      codesOfDefects:
                        type: array
                        items:
                          type: integer
                      pictures:
                        type: array
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                            contentType:
                              type: string
                      additionalDocuments:
                        type: array
                        items:
                          type: object
                          properties:
                            filename:
                              type: string
                            contentType:
                              type: string
        400:
          description: Invalid input data
        404:
          description: Control task not found
        500:
          description: Internal server error

  /api/control_task/{controlTaskId}/defect:
    post:
      summary: Create a new defect related to a control task
      description: Create a new defect for the given control task identified by {controlTaskId}.
      parameters:
        - name: controlTaskId
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier of the control task to which the defect will be added.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: controlTaskId/defect
              properties:
                inspectionDate:
                  type: string
                  format: date
                  description: The date of the inspection for the defect.
                branch:
                  type: string
                  description: The branch where the defect was identified.
                establishment:
                  type: string
                  description: The establishment where the defect was found.
                specialist:
                  type: string
                  description: The specialist responsible for the defect.
                responsiblePerson:
                  type: string
                  description: The person responsible for addressing the defect.
                severity:
                  type: string
                  description: The severity level of the defect.
                repeated:
                  type: boolean
                  description: Indicates if the defect is a repeated issue.
                repeatedFrom:
                  type: string
                  format: date
                  description: The date from which the defect was repeated, if applicable.
                defectCode:
                  type: string
                  description: The code for the defect.
                description:
                  type: string
                  description: The detailed description of the defect.
                note:
                  type: string
                  description: Additional notes related to the defect.
                defectDeadline:
                  type: string
                  format: date
                  description: The deadline for fixing the defect.
                pictures:
                  type: array
                  items:
                    type: object
                    properties:
                      filename:
                        type: string
                        description: The filename of the image.
                      contentType:
                        type: string
                        description: The MIME type of the image.
                      base64Data:
                        type: string
                        description: Base64 encoded image data.
      responses:
        200:
          description: Defect successfully created
          content:
            application/json:
              schema:
                type: object
                title: controlTaskId/defect
                properties:
                  id:
                    type: integer
                    description: A unique identifier for the defect.
                  controlTaskId:
                    type: integer
                    description: The unique identifier of the control task.
                  message:
                    type: string
                    description: Success message indicating that the document was created.
                  inspectionDate:
                    type: string
                    format: date
                  branch:
                    type: string
                  establishment:
                    type: string
                  specialist:
                    type: string
                  responsiblePerson:
                    type: string
                  severity:
                    type: string
                  repeated:
                    type: boolean
                  repeatedFrom:
                    type: string
                    format: date
                  defectCode:
                    type: string
                  description:
                    type: string
                  note:
                    type: string
                  defectDeadline:
                    type: string
                    format: date
                  pictures:
                    type: array
                    items:
                      type: object
                      properties:
                        filename:
                          type: string
                        contentType:
                          type: string
        400:
          description: Invalid input data
        404:
          description: Control task not found
        500:
          description: Internal server error
          
