openapi: 3.0.0
info:
  title: CIVOP API
  version: 1.0.0
  description: API for managing control tasks

paths:
  /document:
    post:
      summary: Creates a control record, saving results and generating unique documentId.
      description: >
        Accepts a supplier's task civopControlTaskId and title, generates a unique internal control task identifier `documentId`, and returns it for use in creating related documents and recording potential defects.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - civopControlTaskId
                - title
                - filename
                - contentType
                - base64Data
              properties:
                civopControlTaskId:
                  type: integer
                title:
                  type: string
                specialist:
                  type: string
                branch:
                  type: string
                establishment:
                  type: string
                inspectionDate:
                  type: string
                  format: date
                interval:
                  type: integer
                numberOfDefects:
                  type: integer
                codesOfDefects:
                  type: array
                  items:
                    type: integer
                filename:
                  type: string
                contentType:
                  type: string
                base64Data:
                  type: string
      responses:
        '200':
          description: Successfully created control task and document.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer                
                  civopControlTaskId:
                    type: integer
                  title:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  specialist:
                    type: string
                  branch:
                    type: string
                  establishment:
                    type: string
                  inspectionDate:
                    type: string
                    format: date
                  repeatedYN:
                    type: boolean
                  numberOfDefects:
                    type: integer
                  codesOfDefects:
                    type: array
                    items:
                      type: integer
                  filename:
                    type: string
                  contentType:
                    type: string
                   
        '500':
          description: Server error while processing the control task.
        '400':
          description: Bad request.

  /document/{documentId}/additionalDocument:
    post:
      summary: Create a new document related to a control task
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier of the control task to which the document will be added.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filename
                - contentType
                - base64Data
              properties:
                filename:
                  type: string
                contentType:
                  type: string
                base64Data:
                  type: string
      responses:
        '200':
          description: Document successfully created and attached to the control task.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  documentId:
                    type: integer
                  filename:
                    type: string
                  contentType:
                    type: string
                  created_at:
                    type: string
                    format: date-time      
        '500':
          description: Server error while saving the document.
        '400':
          description: Bad request.

  /document/{documentId}/picture:
    post:
      summary: Create a new picture related to a control task
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier of the control task to which the picture will be added.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filename
                - contentType
                - base64Data
              properties:
                filename:
                  type: string
                contentType:
                  type: string
                base64Data:
                  type: string
      responses:
        '200':
          description: Picture successfully created and attached to the control task.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  documentId:
                    type: integer
                  filename:
                    type: string
                  contentType:
                    type: string
                  created_at:
                    type: string
                    format: date-time

        '500':
          description: Server error while saving the picture.
        '400':
          description: Bad request.

  /document/{documentId}/defect:
    post:
      summary: Create a new defect related to a control task
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
          description: The unique identifier of the control task to which the defect will be added.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                inspectionDate:
                  type: string
                  format: date
                branch:
                  type: string
                establishment:
                  type: string
                specialist:
                  type: string
                responsiblePerson:
                  type: string
                severity:
                  type: string
                repeated:
                  type: boolean
                repeatedFrom:
                  type: string
                  format: date
                defectCode:
                  type: integer
                description:
                  type: string
                note:
                  type: string
                defectDeadline:
                  type: string
                  format: date
      responses:
        '200':
          description: Defect successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  documentId:
                    type: integer
                  title:
                    type: string
                  inspectionDate:
                    type: string
                    format: date
                  branch:
                    type: string
                  establishment:
                    type: string
                  specialist:
                    type: string
                  responsiblePerson:
                    type: string
                  severity:
                    type: string
                  repeated:
                    type: boolean
                  repeatedFrom:
                    type: string
                    format: date
                  defectCode:
                    type: integer
                  description:
                    type: string
                  note:
                    type: string
                  defectDeadline:
                    type: string
                    format: date
        '500':
          description: Internal server error
        '400':
          description: Bad request.

  /document/{documentId}/defect/{defectId}/picture:
    post:
      summary: Add a new picture related to a defect in a control task
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
        - name: defectId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
                  required:
                    - filename
                    - contentType
                    - base64Data
                  properties:
                    filename:
                      type: string
                    contentType:
                      type: string
                    base64Data:
                      type: string
      responses:
        '200':
          description: Picture successfully added to the defect.
          content:
             application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  defectId:
                    type: integer
                  documentId:
                    type: integer
                  filename:
                    type: string
                  contentType:
                    type: string
                  created_at:
                    type: string
                    format: date-time                      

        '500':
          description: Internal server error
        '400':
          description: Bad request.

  /document/{documentId}/defect/{defectId}:
    put:
      summary: Update an existing defect related to a control task
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
        - name: defectId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                inspectionDate:
                  type: string
                  format: date
                branch:
                  type: string
                establishment:
                  type: string
                specialist:
                  type: string
                responsiblePerson:
                  type: string
                severity:
                  type: string
                repeated:
                  type: boolean
                repeatedFrom:
                  type: string
                  format: date
                defectCode:
                  type: integer
                description:
                  type: string
                note:
                  type: string
                defectDeadline:
                  type: string
                  format: date
      responses:
        '200':
          description: Defect successfully updated
          content:
            application/json:
              schema:
                type: object
                properties:
                   
                  id:
                    type: integer
                    description:  Defect ID (same as defectId when not archived)
                  documentId:
                    type: integer 
                  archived:
                    type: boolean
                  archivedId:
                    type: integer
                    nullable: true
                    description: ID of the archived row, present only when archived=true                                    
                  title:
                    type: string
                  inspectionDate:
                    type: string
                    format: date
                  branch:
                    type: string
                  establishment:
                    type: string
                  specialist:
                    type: string
                  responsiblePerson:
                    type: string
                  severity:
                    type: string
                  repeated:
                    type: boolean
                  repeatedFrom:
                    type: string
                    format: date
                  defectCode:
                    type: integer
                  description:
                    type: string
                  note:
                    type: string
                  defectDeadline:
                    type: string
                    format: date
     
        '500':
          description: Internal server error while updating the defect
        '400':
          description: Bad request.
